

pipeline:

  # Install required modules, as a small test:
  compile:
    image: docker.stackdot.com/lib/node:6.3.1
    commands:
      - npm update
      
  # Publish package
  npm:
    image: plugins/npm