
pipeline:
  compile:
    image: docker.stackdot.com/lib/node:6.3.1
    commands:
      - npm update
      - npm test

<% if(dockerRepoName != ''){ %>
  # Publish to Docker
  docker:
    image: plugins/docker
    repo: docker.stackdot.com/<%=dockerRepoName%>
    tag:
      - '${DRONE_BRANCH/master/latest}'
      - '${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}'
    storage_driver: overlay
    when:
      branch: master
<% } %>
<% if(publishNPM == true){ %>
  # Publish NPM package
  npm:
    image: plugins/npm
<% } %>

  # deploy:
  #   image: vallard/drone-kube
  #   template: kube.yml
  #   namespace: polygon
  #   when:
  #     branch: master
